### PR TITLE
Scheduling notebook

### PR DESCRIPTION
**Pull request by galleon**
- [x] Removing prints from code
- [x] Using async call to MZN so that it is usable in Notebooks
- [x] Telling right story for user

### CODE REVIEW

**Comment by galleon** [comment]
[Binder](https://mybinder.org/v2/gh/airbus/scikit-decide/binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fgalleon%252Fscikit-decide%26urlpath%3Dtree%252Fscikit-decide%252Fnotebooks%252Fscheduling_demo.ipynb%26branch%3Dscheduling)

**Comment by POPOGO** [comment]
The cleaning of debug strings notably in discrete-optimisation part is interesting to include. The notebook is not ready so I can't approve this PR for now.

**Review by dbarbier — APPROVED** [review]
LGTM but please squash all commits which modify notebooks/* into a single one to make history cleaner.

**Comment by galleon** [comment]
Commit history has been rewritten. The binder is provided but a new version will have to be issued as bug fixes are provided in the branch. The last solver will work only with a local install.

**Comment by galleon** [comment]
Code changes have been moved to #97

**Review by g-poveda — APPROVED** [review]

**Pull request merged**
