### PR TITLE
Fixing multiple problems in doc

### PR DESCRIPTION
**Pull request by galleon**
- typo in workflow
- re-instating version tag in navbar
- typo in name of default branch

### CODE REVIEW

**Review by dbarbier — COMMENTED** [review]
Commit message of b508bca is misleading, it seems to imply that there is a bug to fix, but this is not the case. This code works with any label; you can change "main" to "master" if you want, but this is cosmetics.

**Review by dbarbier — APPROVED** [review]

**Comment by dbarbier** [comment]
In fact it would be better to drop the "token" option of deploy, it is useless and may break if there is an error in secrets.

**Comment by dbarbier** [comment]
You may also drop "tokem" from release.yml ;-)

**Comment by galleon** [comment]
> You may also drop "tokem" from release.yml ;-)

Oops :-) Fixed

**Comment by dbarbier** [comment]
Looks good.

**Pull request merged**
