### PR TITLE
Integration of new notebooks in doc

### PR DESCRIPTION
**Pull request by nhuet**
The new notebooks available in "notebooks/" folder will replace the previous small notebooks generated from python scripts in "examples/" folder.

The autodoc.py script is used to:
- list the notebooks and sort them alphabetically
- extract from first cell (which should be a markdown cell)
  - a title (first line if starting with "# ")
  - a description (the other lines)
- generate links
  - to get the notebook from github
  - to launch the notebook with binder
- modify the "guide" page by inserting this list with titles, description, and links,
  in "examples" section (a template will now be used to generate the docs/guide/README.md)
  More precisely, docs/guide/README.md is generated from docs/guide/README.md.template
  where placeholder [[notebooks-list]] is replaced by this list of notebooks

In order to have working links, some environment variables are needed to specify
- repository and branch used to host the binder environment
  -> if not defined, autodoc.py falls back to airbus/scikit-decide:binder
- repository and branch used to fetch the notebooks contents
  -> if not defined, autodoc.py does not generate github+binder links
     and issues a warning

README.md is updated to:
- explain how to define properly the environment variables to build the
  doc
- mention the notebooks in examples section

To test this PR, you can build the documentation locally by typing from root directory:
```shell
export AUTODOC_BINDER_ENV_GH_REPO_NAME="airbus/scikit-decide"
export AUTODOC_BINDER_ENV_GH_BRANCH="binder"
export AUTODOC_NOTEBOOKS_REPO_URL="https://github.com/nhuet/scikit-decide"
export AUTODOC_NOTEBOOKS_BRANCH="nh/doc_notebooks_integration"
yarn install
poetry run python docs/autodoc.py
yarn docs:dev
```
provided you have already installed the library in developer mode with poetry as explained in README.md.

To generate the online doc, the environment variables "AUTODOC_NOTEBOOKS_REPO_URL" and "AUTODOC_NOTEBOOKS_BRANCH" will have to be properly defined by the workflow to correspond to the repository and branch from which it is triggered, and for which the doc is generated. This update of online doc generation should be done in another PR.

### CODE REVIEW

**Review by dbarbier — APPROVED** [review]

**Comment by nhuet** [comment]
In order to make a choice, I created several versions of the website regarding the 2 proposals by @galleon, 
namely (as I understood)
- having a separate page for examples or notebooks
- discarding title/description extraction to keep to only filename+binder link table

To have a real list, i added the maze notebook in the list (see my branch nh/another_doc_notebooks_integration).
The different versions are: 
- [doc-notebooks-integrated-in-guide-page.zip](https://github.com/airbus/scikit-decide/files/7461533/doc-notebooks-integrated-in-guide-page.zip): 
  the current version proposed in the PR, with the list of notebooks directly integrated in the guide page + a title and description from notebooks 1st cell
- [doc-examples-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461530/doc-examples-on-separate-page.zip): 
  the entire examples section is put in a separated page, an examples link appears in the top right navbar, 
  and the guide page examples section contains only a link to this page
- [doc-notebooks-without-title-nor-description-integrated-in-guide-page.zip](https://github.com/airbus/scikit-decide/files/7461550/doc-notebooks-without-title-nor-description-integrated-in-guide-page.zip): 
  notebooks list is integrated in guide page, but no more title and description made 
  (as this PR do if the 1st cell of a notebook is not a markdown cell)
- [doc-notebooks-only-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461547/doc-notebooks-only-on-separate-page.zip): 
  only the notebooks list is deported on a separate page (as it was before this PR) with title + description extraction
- [doc-notebooks-without-title-nor-description-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461554/doc-notebooks-without-title-nor-description-on-separate-page.zip): 
  only the notebooks list is deported on a separate page (as it was before this PR) and only filename and binder links are displayed. 

To see the resulting websites do as follows (as in PR #88):
- Extract the chosen website version in a dedicated directory and serve it locally:
```shell
mkdir testdoc
cd testdoc
unzip path/to/doc-you-want-to-review.zip -d scikit-decide
python -m http.server
```
- Go to http://localhost:8000/scikit-decide/

I prefer [doc-notebooks-integrated-in-guide-page.zip](https://github.com/airbus/scikit-decide/files/7461533/doc-notebooks-integrated-in-guide-page.zip) 
and [doc-examples-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461530/doc-examples-on-separate-page.zip), 
with perhaps a slight preference for [doc-examples-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461530/doc-examples-on-separate-page.zip) 
as it adds more visibility by having a link to examples page on the top right menu. 
But the other one including everything is also ok for me as the notebooks list is still very short.

Note also that, with the current state of the PR, if the first cell of a notebook is not a markdown cell, 
no title nor description will be extracted so that it will fall back to filename + binder link only view. 
So the 2 proposal (having title+description or not) are actually not contradictory.

**Comment by nhuet** [comment]
Here are some screenshots:

### [doc-notebooks-integrated-in-guide-page.zip](https://github.com/airbus/scikit-decide/files/7461533/doc-notebooks-integrated-in-guide-page.zip)
doc-notebooks-integrated-in-guide-page-1
doc-notebooks-integrated-in-guide-page_2
doc-notebooks-integrated-in-guide-page-3

### [doc-examples-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461530/doc-examples-on-separate-page.zip)
doc-examples-on-separate-page_1b
doc-examples-on-separate-page_2b

### [doc-notebooks-without-title-nor-description-integrated-in-guide-page.zip](https://github.com/airbus/scikit-decide/files/7461550/doc-notebooks-without-title-nor-description-integrated-in-guide-page.zip)
doc-notebooks-without-title-nor-description-integrated-in-guide-page_1b

### [doc-notebooks-without-title-nor-description-on-separate-page.zip](https://github.com/airbus/scikit-decide/files/7461554/doc-notebooks-without-title-nor-description-on-separate-page.zip)
doc-notebooks-without-title-nor-description-on-separate-page_1b
doc-notebooks-without-title-nor-description-on-separate-page_2b

**Comment by dbarbier** [comment]
I prefer the last one doc-notebooks-without-title-nor-description-on-separate-page.zip

**Comment by galleon** [comment]
Same for me I have a preference for the last one with probably some couple lines of text explaining how users can replicate the experiments on their machine  (we can simply add a `requirements-notebooks.txt` in the notebooks dir and few lines of explanations)

**Comment by nhuet** [comment]
Waiting for decision about the way to organize docs. Will be done in a later PR.

**Pull request closed without merging**
