### PR TITLE
[Trivial] Make doc generation easier for a VuePress developper

### PR DESCRIPTION
**Pull request by galleon**
A VuePress developper will use either `yarn run docs:dev` to test the documentation or `yarn run docs:build`to generate it. It seems natural to integrate the generation of the `_state.json`  file read by `docs/.vuepress/enhanceApp.js` into that process.

### CODE REVIEW

**Comment by neo-alex** [comment]
> It seems natural to integrate the generation of the `_state.json`

I see your point @galleon but one could argue that all files generated by `autodoc.py` (incl. `_state.json`) are necessary to have the full documentation properly running, thus I wonder if it is worth doing an exception for this file?

**Comment by dbarbier** [comment]
That being said, the same problem occurs if one runs `vuepress dev docs` directly.

**Comment by galleon** [comment]
Included in #72 as suggested

**Comment by dbarbier** [comment]
That is not what I suggested.

**Review by dbarbier — APPROVED** [review]
Thanks, this PR is now minimal and should hopefully not conflict with other PR, it can be merged.

**Pull request merged**
