### PR TITLE
Update notebooks to integrate them more easily in doc

### PR DESCRIPTION
**Pull request by nhuet**
- rename and number notebooks using 2 digits to ease sorting them,
  we let the 00-09 numbers for quick start notebooks which will be the
  ones  previously generated from python scripts in examples
- scheduling notebook:
  - move main title and description in first cell (for auto-extraction
    by autodoc.py)
  - remove commented cell
  - add a level to all titles (by adding a #)
    so that only the main title is a html H1
  - bonus: when using the toc from jupyter nbextensions,
    the title will not be numbered (as a H1) and the other
    section titles will be well numbered

### CODE REVIEW

**Comment by neo-alex** [comment]
OK to merge, thanks

**Comment by dbarbier** [comment]
You made changes in scheduling notebook, please provide a link to binder to help reviewers.

**Comment by nhuet** [comment]
- scheduling notebook for this PR: [Binder](https://mybinder.org/v2/gh/airbus/scikit-decide/binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fnhuet%252Fscikit-decide%26urlpath%3Dtree%252Fscikit-decide%252Fnotebooks%252F13_scheduling_tuto.ipynb%26branch%3Dnh%252Fnotebooks_modif_for_integration)
- scheduling notebok from master [Binder](https://mybinder.org/v2/gh/airbus/scikit-decide/binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fairbus%252Fscikit-decide%26urlpath%3Dtree%252Fscikit-decide%252Fnotebooks%252F03_scheduling_tuto.ipynb%26branch%3Dmaster)

**Review by dbarbier — APPROVED** [review]
Thanks, looks much better indeed with this PR.

**Pull request merged**
